name: CustomStatus
version: '2.0'
main: de.adrian.customstatus.CustomStatus
api-version: '1.20'
commands:
  status:
    description: Setzte deinen Status im TAB
  removestatus:
    description: Entferne den Status von jemandem
  addstatus:
    description: Erstelle einen neuen Status
  deletestatus:
    description: Entferne einen Status